//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finex.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardTypeMaster
    {
        public CardTypeMaster()
        {
            this.Claims = new HashSet<Claim>();
            this.DocumentTypeMasters = new HashSet<DocumentTypeMaster>();
            this.PolicyMasters = new HashSet<PolicyMaster>();
        }
    
        public int CardTypeId { get; set; }
        public string CardTypeName { get; set; }
    
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual ICollection<DocumentTypeMaster> DocumentTypeMasters { get; set; }
        public virtual ICollection<PolicyMaster> PolicyMasters { get; set; }
    }
}
