//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finex.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimReverseFeed
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public string FeedId { get; set; }
        public string RecordType { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> ClaimIntimationDate { get; set; }
        public Nullable<decimal> ClaimEstimatedAmount { get; set; }
        public Nullable<System.DateTime> FileSubDate { get; set; }
        public Nullable<decimal> AssessedAmount { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentMode { get; set; }
        public string PayeeType { get; set; }
        public string PayeePartyCode { get; set; }
        public string PayeePartyName { get; set; }
        public string InvoiceNumber { get; set; }
        public string ChequePayementNumber { get; set; }
        public Nullable<System.DateTime> AccidentDate { get; set; }
    
        public virtual Claim Claim { get; set; }
    }
}
