//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finex.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Claims = new HashSet<Claim>();
            this.DocumentUploads = new HashSet<DocumentUpload>();
            this.OTPs = new HashSet<OTP>();
        }
    
        public int CustId { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
    
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual ICollection<DocumentUpload> DocumentUploads { get; set; }
        public virtual ICollection<OTP> OTPs { get; set; }
    }
}
