//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finex.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntimationTransaction
    {
        public long Id { get; set; }
        public string TransactionNumber { get; set; }
        public string Messgae { get; set; }
        public string TypeOfService { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ClaimId { get; set; }
    }
}
