//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finex.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LossTypeMaster
    {
        public LossTypeMaster()
        {
            this.Claims = new HashSet<Claim>();
            this.Claims1 = new HashSet<Claim>();
            this.CardLossPolicyMappings = new HashSet<CardLossPolicyMapping>();
        }
    
        public int LossTypeId { get; set; }
        public string LossType { get; set; }
        public Nullable<int> CardTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ParentLossTypeId { get; set; }
        public Nullable<bool> IsNatureOfLoss { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual ICollection<Claim> Claims1 { get; set; }
        public virtual ICollection<CardLossPolicyMapping> CardLossPolicyMappings { get; set; }
    }
}
