//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finex.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyMaster
    {
        public PolicyMaster()
        {
            this.Claims = new HashSet<Claim>();
            this.CardLossPolicyMappings = new HashSet<CardLossPolicyMapping>();
        }
    
        public int PolicyId { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<int> CardTypeId { get; set; }
        public string PolicyType { get; set; }
    
        public virtual CardTypeMaster CardTypeMaster { get; set; }
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual ICollection<CardLossPolicyMapping> CardLossPolicyMappings { get; set; }
    }
}
