//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finex.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public UserMaster()
        {
            this.Passwords = new HashSet<Password>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Password> Passwords { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
